name: Deploy

on:
  workflow_run:
    workflows: ["Teste PHP, Login e Banco"]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar PHP
        run: sudo apt-get install -y php-cli php-curl php-mbstring

      - name: Criar pasta de logs e salvar arquivo
        run: |
          mkdir -p public_html/logs
          echo "Deploy executado com sucesso em $(date)" > public_html/logs/deploy.txt
      
      - name: Commit e Push dos logs
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add public_html/logs/
          git commit -m "Adiciona logs de deploy"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      
